// Auto-generated by Supabase CLI — regenerate with:
// npx supabase gen types typescript --linked > apps/web/src/types/database.types.ts
//
// This is a placeholder. Run the command above after `supabase db push`.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          tier: "free" | "pro"
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_status: "none" | "active" | "past_due" | "canceled" | "trialing"
          subscription_period_end: string | null
          preferred_language: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          tier?: "free" | "pro"
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: "none" | "active" | "past_due" | "canceled" | "trialing"
          subscription_period_end?: string | null
          preferred_language?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          tier?: "free" | "pro"
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: "none" | "active" | "past_due" | "canceled" | "trialing"
          subscription_period_end?: string | null
          preferred_language?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      videos: {
        Row: {
          id: string
          user_id: string
          original_filename: string
          storage_path: string
          mime_type: string
          file_size_bytes: number
          duration_seconds: number
          width: number | null
          height: number | null
          status: "uploaded" | "processing" | "completed" | "failed"
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          original_filename: string
          storage_path: string
          mime_type: string
          file_size_bytes: number
          duration_seconds: number
          width?: number | null
          height?: number | null
          status?: "uploaded" | "processing" | "completed" | "failed"
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          original_filename?: string
          storage_path?: string
          mime_type?: string
          file_size_bytes?: number
          duration_seconds?: number
          width?: number | null
          height?: number | null
          status?: "uploaded" | "processing" | "completed" | "failed"
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "videos_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          id: string
          user_id: string
          video_id: string
          status: "queued" | "processing" | "completed" | "failed"
          progress: number
          error_message: string | null
          retry_count: number
          options: Json
          output_storage_path: string | null
          output_duration_seconds: number | null
          output_width: number | null
          output_height: number | null
          transcription: Json | null
          queued_at: string
          started_at: string | null
          completed_at: string | null
          processing_duration_ms: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          video_id: string
          status?: "queued" | "processing" | "completed" | "failed"
          progress?: number
          error_message?: string | null
          retry_count?: number
          options?: Json
          output_storage_path?: string | null
          output_duration_seconds?: number | null
          output_width?: number | null
          output_height?: number | null
          transcription?: Json | null
          queued_at?: string
          started_at?: string | null
          completed_at?: string | null
          processing_duration_ms?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          video_id?: string
          status?: "queued" | "processing" | "completed" | "failed"
          progress?: number
          error_message?: string | null
          retry_count?: number
          options?: Json
          output_storage_path?: string | null
          output_duration_seconds?: number | null
          output_width?: number | null
          output_height?: number | null
          transcription?: Json | null
          queued_at?: string
          started_at?: string | null
          completed_at?: string | null
          processing_duration_ms?: number | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_video_id_fkey"
            columns: ["video_id"]
            isOneToOne: false
            referencedRelation: "videos"
            referencedColumns: ["id"]
          },
        ]
      }
      subscription_events: {
        Row: {
          id: string
          user_id: string | null
          stripe_event_id: string
          event_type: string
          payload: Json
          processed_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          stripe_event_id: string
          event_type: string
          payload: Json
          processed_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          stripe_event_id?: string
          event_type?: string
          payload?: Json
          processed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscription_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
